---
configurations:
  ap-bg-1:
    config: linksys
    ip: 10.20.0.200
    wlans:
      0:
        bssid: 02:00:0f:20:16:00
        channel: 36
      1:
        bssid: 02:00:0f:20:16:01
        channel: 1
    mixins:
      - all
      - linksys
      - linksys-dual-trunk
  ap-bg-2:
    config: dap2965
    ip: 10.20.0.201
    wlans:
      0:
        bssid: 02:00:0f:20:16:10
        channel: 52
      1:
        bssid: 02:00:0f:20:16:11
        channel: 9
    mixins:
      - all
      - dap2965
      - dap2965-video
  ap-bg-3:
    config: dap2965
    ip: 10.20.0.202
    wlans:
      0:
        bssid: 02:00:0f:20:16:20
        channel: 116
      1:
        bssid: 02:00:0f:20:16:21
        channel: 13
    mixins:
      - all
      - dap2965
      - dap2965-single-trunk
  ap-bg-4:
    config: linksys
    ip: 10.20.0.203
    wlans:
      0:
        bssid: 02:00:0f:20:16:30
        channel: 116
      1:
        bssid: 02:00:0f:20:16:31
        channel: 13
    mixins:
      - all
      - linksys
      - linksys-dual-trunk-video
  ap-c-1:
    config: linksys
    ip: 10.20.0.204
    wlans:
      0:
        bssid: 02:00:0f:20:16:40
        channel: 36
      1:
        bssid: 02:00:0f:20:16:41
        channel: 1
    mixins:
      - all
      - linksys
      - linksys-single-trunk
  ap-c-2:
    config: archer-c5
    ip: 10.20.0.205
    wlans:
      0:
        bssid: 02:00:0f:20:16:50
        channel: 116
      1:
        bssid: 02:00:0f:20:16:51
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-mu-1:
    config: archer-c5
    ip: 10.20.0.206
    wlans:
      0:
        bssid: 02:00:0f:20:16:60
        channel: 36
      1:
        bssid: 02:00:0f:20:16:61
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-ma-1:
    config: archer-c5
    ip: 10.20.0.207
    wlans:
      0:
        bssid: 02:00:0f:20:16:70
        channel: 36
      1:
        bssid: 02:00:0f:20:16:71
        channel: 1
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-l0-1:
    config: archer-c5
    ip: 10.20.0.208
    wlans:
      0:
        bssid: 02:00:0f:20:16:80
        channel: 13
      1:
        bssid: 02:00:0f:20:16:81
        channel: 100
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  # ap-lobby1-2-legacy:
  #   config: rs
  #   ip: 10.20.0.209
  #   wlans:
  #     0:
  #       bssid: 02:00:0f:20:16:90
  #       channel: 5
  #   mixins:
  #     - all
  #     - rs
  ap-l0-2:
    config: archer-c5
    ip: 10.20.0.210
    wlans:
      0:
        bssid: 02:00:0f:20:16:a0
        channel: 108
      1:
        bssid: 02:00:0f:20:16:a1
        channel: 9
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-l1-1:
    config: archer-c5
    ip: 10.20.0.211
    wlans:
      0:
        bssid: 02:00:0f:20:16:b0
        channel: 100
      1:
        bssid: 02:00:0f:20:16:b1
        channel: 13
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-noc-1:
    config: archer-c5
    ip: 10.20.0.212
    wlans:
      0:
        bssid: 02:00:0f:20:16:c0
        channel: 100
      1:
        bssid: 02:00:0f:20:16:c1
        channel: 13
    mixins:
      - all
      - archer-c5
      - archer-c5-single-trunk
  ap-l1-2:
    config: linksys
    ip: 10.20.0.213
    wlans:
      0:
        bssid: 02:00:0f:20:16:d0
        channel: 108
      1:
        bssid: 02:00:0f:20:16:d1
        channel: 1
    mixins:
      - all
      - linksys
      - linksys-single-trunk
